import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import { TernSecureProvider } from '@tern-secure-node/nextjs';
import { Header} from '@/components/header';
import './globals.css';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <TernSecureProvider
          requiresVerification={false}
          isTernSecureDev={true}
          persistence='browserCookie'
          //afterSignOutUrl='/sign-in'  //better use it on client-side
        >
          <Header />
          {children}
        </TernSecureProvider>
      </body>
    </html>
  );
}
